# ---------- Builder ----------
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# build arguments
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SOCKET_URL
ARG NEXT_PUBLIC_OMISE_PUBLIC_KEY
ARG NEXTAUTH_SECRET
ARG DOMAIN
ARG NODE_ENV
ARG PORT

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_OMISE_PUBLIC_KEY=$NEXT_PUBLIC_OMISE_PUBLIC_KEY
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV DOMAIN=$DOMAIN
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT

RUN npm run build


# ---------- Production ----------
FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_SOCKET_URL
ARG NEXT_PUBLIC_OMISE_PUBLIC_KEY
ARG NEXTAUTH_SECRET
ARG DOMAIN
ARG NODE_ENV
ARG PORT

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_SOCKET_URL=$NEXT_PUBLIC_SOCKET_URL
ENV NEXT_PUBLIC_OMISE_PUBLIC_KEY=$NEXT_PUBLIC_OMISE_PUBLIC_KEY
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV DOMAIN=$DOMAIN
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.js ./next.config.js

EXPOSE 3000

CMD ["node_modules/.bin/next","start","-p","3000"]